name = "TabularDisplay"
uuid = "3eeacb1d-13c2-54cc-9b18-30c86af3cadb"
authors = ["Tom Kwong <tk3369@gmail.com>"]
version = "1.3.0"

[deps]
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"

[compat]
Format = "~1"
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
